version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest 

    volumes:
      - ./grafana/:/var/lib/grafana/

    
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    ports:
     - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  blackbox:
    image: prom/blackbox-exporter:latest
    privileged: true
    volumes:  
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115


  #postgres:
   # image: postgres:latest
    #ports:
  #    - 5432:5432
   # volumes:  
   #   ./backup:/var/lib/postgressql/data
  #enviroment:
   # POSTGRES_PASSWORD : mayco123
   # POSTGRESS_DB : grafana      
