# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "windows_exporter"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
  - job_name: "servidores_web V01 "
    static_configs:
      - targets: ["localhost:9182"]

  - job_name: "servidores_web C003"
    static_configs:
      - targets: ["192.168.18.218:9182"]

  - job_name: "servidor Srvhv01"
    static_configs:
      - targets: ["192.168.1.209:9182"]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx]  # Especifica el módulo ICMP
    static_configs:
     - targets: ["192.168.1.219:9115","192.168.1.209:9182","localhost:9182","192.168.18.218:9182","192.168.1.224:9182","192.168.1.240:9182","192.168.10.201:9182","192.168.18.218:9182","192.168.2.220:9182","192.168.10.201:9182","192.168.15.202:9182","192.168.3.203:9182","192.168.9.204:9182","192.168.4.205:9182","192.168.5.206:9182","198.168.13.207:9182","192.168.7.209:9182","192.168.7.39:9182","192.168.1:9182","192.168.8.212:9182","192.168.1.213:9182","192.168.16.214:9182","192.168.11.215:9182","192.168.14.211:9182" ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.224:9115                 

      